name: formatting code
on:
  push:
    branches:
    - main
    - 'feat-**'

jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Insatll Dependencies
      run: npm install
    - name: Install packages
      run: npm ci
    - name: Prettier
      run: npm run format
    - name: Lint
      run: npm run lint